spring:
  application:
    name: Backend

#  datasource:
#    url: ${MY_DB_URL}
#    driver-class-name: org.postgresql.Driver
#    username: ${MY_DB_UNAME}
#    password: ${MY_DB_PWD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
server:
  port: 8080
logging:
  level:
    root: info
    dev:
      sajid:
        backend: debug
  file:
    name: logs/app.log

app:
  jwt-secret: ${MY_SECRET_KEY}
  jwt-expiration-ms: 36000000
